version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  tests:
    jobs:
      - helloworld
      - install_yarn
      - lint
      - test
      -db
      
      
jobs:
    helloworld:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - run: echo "hello world"
            
            
            
    install_yarn:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - restore_cache: 
                key: yarn-packages-{{ checksum "yarn.lock" }}
            - run: yarn global add node-gyp
            - run: yarn install
            - save_cache:
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths: 
                    - ./node_modules
                    
                    
                    
    lint:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - restore_cache: 
                key: yarn-packages-{{ checksum "yarn.lock" }}
            - run: yarn lint
            - run: yarn format:check
            
            
            
    test:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - restore_cache: 
                key: yarn-packages-{{ checksum "yarn.lock" }}
            - run: yarn test:ci 
            
            
            
    db:
        docker:
            - image: circleci/node:12
              environment:
                DATABASE_URL: postgres://psqluser:psqlpassword@localhost:5432/psdb
                JWT_SECRET: hi
                API_PORT: 3000
                API_HOST: localhost
                API_PROTOCOL: http
            - image: circleci/postgres:9.6.2-alpine
              environment:
                POSTGRES_USER: psqluser
                POSTGRES_PASSWORD: psqlpassword
                POSTGRES_DB: psdb
        steps:
            - checkout
            - restore_cache: 
                key: yarn-packages-{{ checksum "yarn.lock" }}
            - run: yarn test:e2e
        
        
        
            

