version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  tests:
    jobs:
      - helloworld
      
jobs:
    helloworld:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - run: echo "hello world"

