version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  tests:
    jobs:
      - helloworld
      - install_yarn
      - lint
      - test
      
      
jobs:
    helloworld:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - run: echo "hello world"
            
            
            
    install_yarn:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - restore_cache: 
                key: yarn-packages-{{ checksum "yarn.lock" }}
            - run: yarn global add node-gyp
            - run: yarn install
            - save_cache:
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths: 
                    - ./node_modules
                    
                    
                    
    lint:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - restore_cache: 
                key: yarn-packages-{{ checksum "yarn.lock" }}
            - run: yarn lint
            - run: yarn format:check
            
            
            
    test:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - restore_cache: 
                key: yarn-packages-{{ checksum "yarn.lock" }}
            - run: yarn test:ci 
        
        
            

